var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "cpaciity": "",
    "brand": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1200px-No-Image-Placeholder.svg.png"

}, {
    "id": 1,
    "title": "Apple MacBook Air",
    "price": "65,999",
    "cpaciity": "128gb",
    "RAM": "8GB",
    "Processor": "Core i5",
    "GraphicProcessor": "Intel HD Graphic 6000",
    "OSversion": "Mac OS sierra",
    "Colours": "Starlight, Midnight, Blue, Pink, (PRODUCT)RED",
    "screensize": "13.3 Inch",
    "weight": "1.35 kg",
    "USBports": "2 x USB 3.0",
    "Clockspeed": "1.8GHz",
    "keyboardtype": "Normal",
    "battery": "3,227mAh lithium-ion battery",
    "image": "https://m.media-amazon.com/images/I/71vFKBpKakL._SL1500_.jpg",
    "connectivity": "WiFi 6, Bluetooth 5.0 Wireless technology",
    "webCamera": "720p FaceTime HD camera",
    "batteryLife": "Up to 18 hours Apple TV app movie playback,Up to 12 hours wireless web",
    "display": "2560x1600 native resolution at 227 pixels per inch with support for millions of colours",
    "charging": "Two Thunderbolt / USB 4 ports with support"
}, {
    "id": 2,
    "title": "Apple MacBook Pro",
    "price": "117,400",
    "cpaciity": "256gb",
    "RAM": "8GB",
    "Processor": "Core i5",
    "GraphicProcessor": "Intel Iris Graphic 6100",
    "OSversion": "Mac OS X Yosemite",
    "Colours": "Starlight, Midnight, Blue, Pink, (PRODUCT)RED",
    "screensize": "13 Inch",
    "weight": "1.58 kg",
    "USBports": "2 x USB 3.0",
    "Clockspeed": "2.7GHz with Turbo Boost Upto 3.2GHz",
    "keyboardtype": "Backlit",
    "battery": "3,227mAh lithium-ion battery",
    "image": "https://m.media-amazon.com/images/I/71an9eiBxpL._SX522_.jpg",
    "connectivity": "WiFi 6, Bluetooth 5.0 Wireless technology",
    "webCamera": "720p FaceTime HD camera",
    "batteryLife": "Up to 20 hours Apple TV app movie playback,Up to 17 hours wireless web",
    "display": "2560x1600 native resolution at 227 pixels per inch with support for millions of colours",
    "charging": "Two Thunderbolt / USB 4 ports with support"

}, {
    "id": 3,
    "title": "HP Pavilion 15",
    "price": "79,500",
    "cpaciity": "128GB SSD, 1TB HDD",
    "RAM": "8GB",
    "Processor": "Core i5",
    "GraphicProcessor": "NVIDIA Geforce GTX 1050",
    "OSversion": "Windows 10",
    "Colours": "BLACK",
    "screensize": "13 Inch",
    "weight": "2.17 kg",
    "USBports": "3 x USB 3.0",
    "Clockspeed": "4GHz",
    "keyboardtype": "Purple Backlit",
    "battery": "4-cell, 70 Wh li-ion polymer battery",
    "image": "https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/6/D/6D4K8PA-1_T1656564494.png",
    "connectivity": "Wi-Fi standards supported, 4.2 Bluetooth version",
    "webCamera": "0.3-megapixel",
    "batteryLife": "3.5(hours)",
    "display": "diagonal FHD IPS WLED-backlit touch screen (1920 x 1080)",
    "charging": "Type-C"

}, {
    "id": 4,
    "title": "HP Victus",
    "price": "79,500",
    "cpaciity": "512gb",
    "HDD cpaciity": "-",
    "RAM": "8GB",
    "Processor": "AMD Ryzen 5 5600H ",
    "GraphicProcessor": "4GB Raedon RX5500M",
    "OSversion": "Windows 10",
    "Colours": "BLACK",
    "screensize": "16.1 Inch",
    "weight": "2.46 kg",
    "USBports": "2 x USB 3.0",
    "Clockspeed": "144Hz",
    "keyboardtype": "Backlit",
    "battery": "4-cell, 70 Wh li-ion polymer battery",
    "image": "https://m.media-amazon.com/images/I/71D9lGfC5qL._SL1500_.jpg",
    "connectivity": "Realtek Wi-Fi CERTIFIED 6™ (2x2) and Bluetooth® 5.2 combo (Supporting Gigabit data rate)",
    "webCamera": "HP Wide Vision 720p HD camera with integrated dual array digital microphones",
    "batteryLife": "Up to 8 hours and 45 minutes",
    "display": "144 Hz, 7 ms response time, IPS, micro-edge, anti-glare, Low Blue Light, 300 nits, 100% sRGB",
    "charging": "1 SuperSpeed USB Type-A 5Gbps signaling rate (HP Sleep and Charge)"

}, {
    "id": 5,
    "title": "Lenovo IdeaPad Gaming 3",
    "price": "79,500",
    "cpaciity": "512gb",
    "HDD cpaciity": "-",
    "RAM": "8GB",
    "Processor": "AMD Ryzen 5 5600H ",
    "GraphicProcessor": "4GB NVIDIA RTX 3050",
    "OSversion": "Windows 11",
    "Colours": "SHADOW BLACK",
    "screensize": "15.6 Inch",
    "weight": "2.25 kg",
    "USBports": "2 x USB 3.0",
    "Clockspeed": "3.3GHz",
    "keyboardtype": "RGB Backlit",
    "battery": "6-cell, li-ion polymer battery",
    "image": "https://m.media-amazon.com/images/I/71--IQUHVwL._SL1500_.jpg",
    "connectivity": "WiFi 802.11 ac ,Bluetooth® 5.1",
    "webCamera": "720 HD webcam with privacy shutter",
    "batteryLife": "Up to 6.7 hours",
    "display": "(1920 x 1080) IPS, 120Hz, 45% NTSC, 250 nits",
    "charging": "USB-C 3.1"

}, {
    "id": 6,
    "title": "Lenovo Legion 5",
    "price": "1,24,341",
    "cpaciity": "1TB",
    "HDD cpaciity": "-",
    "RAM": "16GB",
    "Processor": "AMD Ryzen 7 5800H ",
    "GraphicProcessor": "6GB NVIDIA RTX 3060",
    "OSversion": "Windows 11",
    "Colours": "SHADOW BLACK",
    "screensize": "15.6 Inch",
    "weight": "2.4 kg",
    "USBports": "3x USB 3.0",
    "Clockspeed": "5 GHz",
    "keyboardtype": "RGB Backlit",
    "battery": "6-cell, li-ion polymer battery",
    "image": "https://m.media-amazon.com/images/I/71fzx0pGY5L._SL1500_.jpg",
    "connectivity": "Wi-Fi 6 (802.11ax), Bluetooth 5.0",
    "webCamera": "User-Facing: 720p",
    "batteryLife": "6.8 Hours",
    "display": "(1920 x 1080) 16:9 Aspect Ratio, 144hz Refresh Rate",
    "charging": "1 x USB 3.1 / USB 3.2 Gen 1 (Supports DisplayPort and Power Delivery)"
}, {
    "id": 7,
    "title": "ASUS ZenBook Pro",
    "price": "84,999",
    "cpaciity": "16GB, 256GB, 512GB, 1TB, 2TB",
    "HDD cpaciity": "-",
    "RAM": "8GB, 16GB, 32GB",
    "Processor": "Intel Core i9",
    "GraphicProcessor": "4GB NVIDIA® GeForce® RTX 3050 Ti",
    "OSversion": "Windows 11",
    "Colours": "SHADOW BLACK",
    "screensize": "14.5 Inch",
    "weight": "1.70 kg",
    "USBports": "1x USB Port, Thunderbold Port, HDMI Port, 3.55mm Audio Jack, Micro SSD",
    "Clockspeed": "5.0 GHz",
    "keyboardtype": "Backlit Chiclet Keyboard",
    "battery": "76WHrs, 4S1P, 4-cell Li-ion",
    "image": "https://m.media-amazon.com/images/I/71QZ23O7rmL._SL1500_.jpg",
    "connectivity": "Dual-band 802.11ac gigabit-class Wi-Fi, Bluetooth 5.0",
    "webCamera": "VGA webcam",
    "batteryLife": "Up to 9.5 hours battery life",
    "display": "LED-backlit 4K UHD (3840 x 2160) 16:9 touchscreen, color calibration: Delta E < 2, 100% Adobe RGB color gamut",
    "charging": "ø4.5 (mm)(Output: 19.5V DC, 7.7A, 150W)"
}, {
    "id": 8,
    "title": "ASUS Zenbook Pro Duo 15 OLED (UX582)",
    "price": "229,990",
    "cpaciity": "1TB M.2 NVME",
    "HDD cpaciity": "-",
    "RAM": "32GB DDR4",
    "Processor": "Intel® Core™ i9-10980HK Processor",
    "GraphicProcessor": "8GB NVIDIA® GeForce® RTX™ 3070",
    "OSversion": "Windows 11",
    "Colours": "Celestial Blue",
    "screensize": "15.6 Inch",
    "weight": "2.34 kg",
    "USBports": "1x USB Port, Thunderbold Port, HDMI Port, 3.55mm Audio Jack",
    "Clockspeed": "5.0 GHz",
    "keyboardtype": "Backlit Chiclet Keyboard",
    "battery": "92WHrs, 4S2P, 8-cell Li-ion",
    "image": "https://m.media-amazon.com/images/I/91A9ac8Q9KL._SL1500_.jpg",
    "connectivity": "HDMI port,Wi-Fi6 802.11ax, Up to 40Gbps Thunderbolt™ 3 data transfers1",
    "webCamera": "HD camera with IR function to support Windows Hello",
    "batteryLife": "71WHrs",
    "display": "4K UHD (3840 x 2160) 16:9 aspect ratio, IPS-level Panel, LED Backlit, 0.2ms response time, 60Hz refresh rate",
    "charging": "1x Thunderbolt™ 3 supports display / power delivery"
}]